// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDO47IboLkMUHJQHddITLogJlUYUOl8vY',
    appId: '1:994683983515:web:204a86eb3a0431abcbd83e',
    messagingSenderId: '994683983515',
    projectId: 'myvoldon',
    authDomain: 'myvoldon.firebaseapp.com',
    storageBucket: 'myvoldon.firebasestorage.app',
    measurementId: 'G-WP8XZWRSG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoo67_hLtL-a49BaDCwJUSbxM3f49K9N4',
    appId: '1:994683983515:android:17e4420859b14de0cbd83e',
    messagingSenderId: '994683983515',
    projectId: 'myvoldon',
    storageBucket: 'myvoldon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVC9PmYmS9TYR_3hev0oR508li1V--dWc',
    appId: '1:994683983515:ios:887b506b9615fb81cbd83e',
    messagingSenderId: '994683983515',
    projectId: 'myvoldon',
    storageBucket: 'myvoldon.firebasestorage.app',
    iosBundleId: 'com.example.voldon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVC9PmYmS9TYR_3hev0oR508li1V--dWc',
    appId: '1:994683983515:ios:887b506b9615fb81cbd83e',
    messagingSenderId: '994683983515',
    projectId: 'myvoldon',
    storageBucket: 'myvoldon.firebasestorage.app',
    iosBundleId: 'com.example.voldon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDO47IboLkMUHJQHddITLogJlUYUOl8vY',
    appId: '1:994683983515:web:cf2819adc8bb4546cbd83e',
    messagingSenderId: '994683983515',
    projectId: 'myvoldon',
    authDomain: 'myvoldon.firebaseapp.com',
    storageBucket: 'myvoldon.firebasestorage.app',
    measurementId: 'G-FVHMKBYDW5',
  );

}